// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnet.Data;

#nullable disable

namespace aspnet.Migrations
{
    [DbContext(typeof(CasinoDbContext))]
    [Migration("20260611131235_UserFirstLastName")]
    partial class UserFirstLastName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("aspnet.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("aspnet.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CasinoId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CasinoId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("aspnet.Models.Casino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FoundedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Casinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ilica 12, Zagreb",
                            FoundedDate = new DateTime(2005, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "HR-CAS-001",
                            Name = "Royal Vegas"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Vukovarska 55, Split",
                            FoundedDate = new DateTime(2010, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "HR-CAS-002",
                            Name = "Golden Palace"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Korzo 3, Rijeka",
                            FoundedDate = new DateTime(2018, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "HR-CAS-003",
                            Name = "Diamond Club"
                        });
                });

            modelBuilder.Entity("aspnet.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CasinoId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CasinoId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CasinoId = 1,
                            FirstName = "Luka",
                            LastName = "Perić",
                            Position = "Dealer"
                        },
                        new
                        {
                            Id = 2,
                            CasinoId = 1,
                            FirstName = "Sara",
                            LastName = "Blažić",
                            Position = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            CasinoId = 1,
                            FirstName = "Josip",
                            LastName = "Matić",
                            Position = "Security"
                        },
                        new
                        {
                            Id = 4,
                            CasinoId = 2,
                            FirstName = "Maja",
                            LastName = "Šimić",
                            Position = "Dealer"
                        },
                        new
                        {
                            Id = 5,
                            CasinoId = 2,
                            FirstName = "Darko",
                            LastName = "Vukić",
                            Position = "Manager"
                        },
                        new
                        {
                            Id = 6,
                            CasinoId = 2,
                            FirstName = "Nikolina",
                            LastName = "Čović",
                            Position = "Cashier"
                        },
                        new
                        {
                            Id = 7,
                            CasinoId = 3,
                            FirstName = "Bruno",
                            LastName = "Knežević",
                            Position = "Dealer"
                        },
                        new
                        {
                            Id = 8,
                            CasinoId = 3,
                            FirstName = "Ivana",
                            LastName = "Turić",
                            Position = "Manager"
                        },
                        new
                        {
                            Id = 9,
                            CasinoId = 3,
                            FirstName = "Ante",
                            LastName = "Grgić",
                            Position = "Security"
                        });
                });

            modelBuilder.Entity("aspnet.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("MaxBet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinBet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Classic card game",
                            MaxBet = 500m,
                            MinBet = 10m,
                            Name = "Blackjack",
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Most popular poker variant",
                            MaxBet = 1000m,
                            MinBet = 20m,
                            Name = "Texas Hold'em",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "European single-zero roulette",
                            MaxBet = 300m,
                            MinBet = 5m,
                            Name = "Roulette",
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Progressive jackpot slots",
                            MaxBet = 50m,
                            MinBet = 1m,
                            Name = "Lucky Slots",
                            Type = 0
                        });
                });

            modelBuilder.Entity("aspnet.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1500m,
                            DateOfBirth = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marko@mail.com",
                            FirstName = "Marko",
                            LastName = "Horvat"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 800m,
                            DateOfBirth = new DateTime(1995, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana@mail.com",
                            FirstName = "Ana",
                            LastName = "Kovač"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 3200m,
                            DateOfBirth = new DateTime(1988, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivan@mail.com",
                            FirstName = "Ivan",
                            LastName = "Babić"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 600m,
                            DateOfBirth = new DateTime(1993, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petra@mail.com",
                            FirstName = "Petra",
                            LastName = "Novak"
                        },
                        new
                        {
                            Id = 5,
                            Balance = 5000m,
                            DateOfBirth = new DateTime(1985, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tomislav@mail.com",
                            FirstName = "Tomislav",
                            LastName = "Jurić"
                        });
                });

            modelBuilder.Entity("aspnet.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TableId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlayerId = 1,
                            ReservedAt = new DateTime(2024, 4, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TableId = 1
                        },
                        new
                        {
                            Id = 2,
                            PlayerId = 2,
                            ReservedAt = new DateTime(2024, 4, 10, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            TableId = 4
                        },
                        new
                        {
                            Id = 3,
                            PlayerId = 3,
                            ReservedAt = new DateTime(2024, 4, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TableId = 7
                        },
                        new
                        {
                            Id = 4,
                            PlayerId = 1,
                            ReservedAt = new DateTime(2024, 4, 12, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            TableId = 5
                        },
                        new
                        {
                            Id = 5,
                            PlayerId = 5,
                            ReservedAt = new DateTime(2024, 4, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            TableId = 2
                        });
                });

            modelBuilder.Entity("aspnet.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CasinoId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxBet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinBet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CasinoId");

                    b.HasIndex("GameId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CasinoId = 1,
                            GameId = 1,
                            IsAvailable = true,
                            MaxBet = 500m,
                            MinBet = 10m,
                            TableNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            CasinoId = 1,
                            GameId = 2,
                            IsAvailable = false,
                            MaxBet = 1000m,
                            MinBet = 20m,
                            TableNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            CasinoId = 1,
                            GameId = 3,
                            IsAvailable = true,
                            MaxBet = 300m,
                            MinBet = 5m,
                            TableNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            CasinoId = 2,
                            GameId = 2,
                            IsAvailable = true,
                            MaxBet = 1000m,
                            MinBet = 20m,
                            TableNumber = 1
                        },
                        new
                        {
                            Id = 5,
                            CasinoId = 2,
                            GameId = 3,
                            IsAvailable = true,
                            MaxBet = 300m,
                            MinBet = 5m,
                            TableNumber = 2
                        },
                        new
                        {
                            Id = 6,
                            CasinoId = 2,
                            GameId = 4,
                            IsAvailable = false,
                            MaxBet = 50m,
                            MinBet = 1m,
                            TableNumber = 3
                        },
                        new
                        {
                            Id = 7,
                            CasinoId = 3,
                            GameId = 1,
                            IsAvailable = true,
                            MaxBet = 500m,
                            MinBet = 10m,
                            TableNumber = 1
                        },
                        new
                        {
                            Id = 8,
                            CasinoId = 3,
                            GameId = 4,
                            IsAvailable = true,
                            MaxBet = 50m,
                            MinBet = 1m,
                            TableNumber = 2
                        },
                        new
                        {
                            Id = 9,
                            CasinoId = 3,
                            GameId = 2,
                            IsAvailable = false,
                            MaxBet = 1000m,
                            MinBet = 20m,
                            TableNumber = 3
                        });
                });

            modelBuilder.Entity("aspnet.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500m,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 200m,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerId = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 450m,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerId = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 300m,
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Amount = 150m,
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 100m,
                            CreatedAt = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1000m,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerId = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Amount = 500m,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerId = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            Amount = 800m,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerId = 3,
                            Type = 3
                        });
                });

            modelBuilder.Entity("aspnet.Models.WaitlistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.ToTable("WaitlistEntries");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("aspnet.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("aspnet.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aspnet.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("aspnet.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("aspnet.Models.Attachment", b =>
                {
                    b.HasOne("aspnet.Models.Casino", "Casino")
                        .WithMany("Attachments")
                        .HasForeignKey("CasinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casino");
                });

            modelBuilder.Entity("aspnet.Models.Employee", b =>
                {
                    b.HasOne("aspnet.Models.Casino", "Casino")
                        .WithMany("Employees")
                        .HasForeignKey("CasinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casino");
                });

            modelBuilder.Entity("aspnet.Models.Reservation", b =>
                {
                    b.HasOne("aspnet.Models.Player", "Player")
                        .WithMany("Reservations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aspnet.Models.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("aspnet.Models.Table", b =>
                {
                    b.HasOne("aspnet.Models.Casino", "Casino")
                        .WithMany("Tables")
                        .HasForeignKey("CasinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aspnet.Models.Game", "Game")
                        .WithMany("Tables")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casino");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("aspnet.Models.Transaction", b =>
                {
                    b.HasOne("aspnet.Models.Player", "Player")
                        .WithMany("Transactions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("aspnet.Models.Casino", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Employees");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("aspnet.Models.Game", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("aspnet.Models.Player", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("aspnet.Models.Table", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
